// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sonhopadaria.Data;

#nullable disable

namespace sonhopadaria.Migrations
{
    [DbContext(typeof(DataBD))]
    [Migration("20241120235824_SonhoPadaria")]
    partial class SonhoPadaria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sonhopadaria.Models.TB_ETIQUETAGEM", b =>
                {
                    b.Property<int>("etiqueta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("etiqueta_id"));

                    b.Property<double>("preco_prod")
                        .HasColumnType("float");

                    b.Property<int>("produto_id")
                        .HasColumnType("int");

                    b.Property<double>("unidade_prod")
                        .HasColumnType("float");

                    b.HasKey("etiqueta_id");

                    b.ToTable("TB_ETIQUETAGEM");
                });

            modelBuilder.Entity("sonhopadaria.Models.TB_FUNCIONARIO", b =>
                {
                    b.Property<int>("funcionario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("funcionario_id"));

                    b.Property<string>("nome_funcionario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("salario")
                        .HasColumnType("float");

                    b.Property<string>("senha_funcionario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("funcionario_id");

                    b.ToTable("TB_FUNCIONARIO");
                });

            modelBuilder.Entity("sonhopadaria.Models.TB_PRODUTO", b =>
                {
                    b.Property<int>("produto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("produto_id"));

                    b.Property<string>("cod_produto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("preco_prod")
                        .HasColumnType("float");

                    b.Property<string>("produto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("qtd_estoque_prod")
                        .HasColumnType("float");

                    b.Property<string>("tipo_prod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("unidade_prod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("produto_id");

                    b.ToTable("TB_PRODUTO");
                });

            modelBuilder.Entity("sonhopadaria.Models.TB_TRASACAO_ESTOQUE", b =>
                {
                    b.Property<int>("transacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("transacao"));

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("produto_id")
                        .HasColumnType("int");

                    b.Property<string>("qtd_transacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_trasacao")
                        .HasColumnType("int");

                    b.HasKey("transacao");

                    b.ToTable("TB_TRASACAO_ESTOQUE");
                });

            modelBuilder.Entity("sonhopadaria.Models.TB_VENDA", b =>
                {
                    b.Property<int>("venda_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("venda_id"));

                    b.Property<DateOnly>("data_venda")
                        .HasColumnType("date");

                    b.Property<int>("funcionario_id")
                        .HasColumnType("int");

                    b.Property<decimal>("total_venda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("venda_id");

                    b.ToTable("TB_VENDA");
                });

            modelBuilder.Entity("sonhopadaria.Models.TB_VENDAS_PRODUTOS", b =>
                {
                    b.Property<int>("venda_prod_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("venda_prod_id"));

                    b.Property<int>("etiqueta_id")
                        .HasColumnType("int");

                    b.Property<double>("preco")
                        .HasColumnType("float");

                    b.Property<int>("produto_id")
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<int>("venda_id")
                        .HasColumnType("int");

                    b.HasKey("venda_prod_id");

                    b.ToTable("TB_VENDAS_PRODUTOS");
                });
#pragma warning restore 612, 618
        }
    }
}
